# Generated by Django 4.0.5 on 2022-07-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clsProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('version', models.CharField(max_length=5)),
                ('documentacion', models.CharField(max_length=40)),
                ('licencia', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tamaño', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
