# Generated by Django 4.0.5 on 2022-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_clsproductos'),
    ]

    operations = [
        migrations.CreateModel(
            name='clsPaquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('numero', models.IntegerField()),
                ('version', models.CharField(max_length=5)),
                ('documentacion', models.CharField(max_length=40)),
                ('licencia', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('tamaño', models.CharField(max_length=20)),
                ('imagen', models.CharField(max_length=30)),
            ],
        ),
    ]
